# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Update sites list

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 1"

permissions:
  contents: read

jobs:
  build:
    name: Run scripts

    # Self-hosted runners get longer job time limits
    # runs-on: [self-hosted, Linux]
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Fetch all sites
        run: |
          python ./scraper.py

      # Merge old and new data to reduce overall number of requests
      # and time taken to run, otherwise we'd exceed GitHub's max
      # run time!
      - name: Combine old data with new sites
        run: |
          python ./merge_old_with_new.py
          mv sites_current.json sites_current.json.new
          mv merged_data.json sites_current.json

      # Remove the merged data file and restore the original new
      # sites JSON file.
      - name: Fetch operator info
        run: |
          python ./metadata_fetcher.py
          rm sites_current.json
          mv sites_current.json.new sites_current.json

      - name: Commit and push dataset
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update scraped sites dataset
          branch: main
