# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Update sites list

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 1"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Fetch all sites
        run: |
          python ./scraper.py

      - name: Fetch operator info
        run: |
          python ./metadata_fetcher.py

      - name: Commit and push dataset
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update scraped sites dataset
          branch: main
